package com.yanggochi.nurs.domain;

/** REQ-06 알림 종류 */
public enum NotificationType { SCHEDULE_CONFIRMED, SCHEDULE_UNCONFIRMED, REQUEST_DECIDED, JOIN_APPROVED, JOIN_REJECTED, DUTY_REMINDER, LOCK_FORCED }
